apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: rajeshRC
spec:
  replicas: 5
  selector: 
    app: tomcat
  template:
    metadata: 
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers: 
      - name: rajesh-tomcat
        image: tomcat
        ports:
        - containerPort: 8080
